import React from 'react'
import { RouteComponentProps, withRouter } from 'react-router-dom'
import { getTransactions } from '../data/store'
import { Transaction } from '../types'

interface SummaryState { loading: boolean; month: string; transactions: Transaction[] }

export class MonthlySummary extends React.Component<RouteComponentProps, SummaryState> {
  public state: SummaryState = { loading: true, month: '2026-09', transactions: [] }
  public componentDidMount() { getTransactions().then((transactions) => this.setState({ transactions, loading: false })) }
  private currency(value: number) { return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value) }
  public render() { if (this.state.loading) return <div className="animate-pulse space-y-5"><div className="h-10 w-56 rounded bg-slate-200" /><div className="h-40 rounded-card bg-slate-200" /></div>; const transactions = this.state.transactions.filter((transaction) => transaction.date.slice(0, 7) === this.state.month); const income = transactions.filter((transaction) => transaction.type === 'Income').reduce((sum, transaction) => sum + transaction.amount, 0); const expenses = transactions.filter((transaction) => transaction.type === 'Expense').reduce((sum, transaction) => sum + transaction.amount, 0); const spend: { [name: string]: number } = {}; transactions.filter((transaction) => transaction.type === 'Expense').forEach((transaction) => { spend[transaction.category] = (spend[transaction.category] || 0) + transaction.amount }); return <div className="max-w-5xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 className="text-3xl font-bold">Monthly summary</h1><p className="mt-2 text-muted">Review a month of income and spending.</p></div><label className="text-sm font-semibold">Month<input type="month" value={this.state.month} onChange={(event) => this.setState({ month: event.target.value })} className="mt-2 block rounded-xl border border-line bg-surface px-3 py-2.5 font-normal" /></label></div><div className="mt-7 grid gap-4 sm:grid-cols-3">{[{ label: 'Income', value: income, color: 'text-income' }, { label: 'Expenses', value: expenses, color: 'text-expense' }, { label: 'Balance', value: income - expenses, color: 'text-primary' }].map((metric) => <article key={metric.label} className="rounded-card border border-line bg-surface p-5 shadow-sm"><p className="text-sm font-medium text-muted">{metric.label}</p><p className={`mt-4 text-2xl font-bold ${metric.color}`}>{this.currency(metric.value)}</p></article>)}</div><section className="mt-6 rounded-card border border-line bg-surface p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Expense breakdown</h2><button onClick={() => this.props.history.push('/transactions')} className="text-sm font-semibold text-primary">View transactions</button></div>{transactions.length === 0 ? <div className="py-10 text-center"><p className="font-semibold">No activity this month</p><p className="mt-1 text-sm text-muted">Try a different month or add a transaction.</p></div> : <div className="mt-5 space-y-4">{Object.keys(spend).map((category) => <div key={category} className="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span className="font-semibold">{category}</span><span className="font-bold text-expense">{this.currency(spend[category])}</span></div>)}</div>}</section></div> }
}

export default withRouter(MonthlySummary)
